name: CI
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm rebuild
    - run: npm run-script gulp
    - run: npm run-script eleventy
    - run: npm run-script copy2020
    - run: npm run-script copy2021
    - run: npm run-script copy2022
    - run: npm run-script copy2023
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAXNR47MADAISLEYYZ
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_FOR_AKIAXNR47MADAISLEYYZ }}
        aws-region: us-east-2
